## CIND830 - Python Programming for Data Science  
### Assignment 3 (10% of the final grade)
### Due on December 07, 2020 11:59 PM

*****
This is a Jupyter Notebook document that extends a simple formatting syntax for authoring HTML and PDF.
Review [this](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) website for more details on using Jupyter Notebook.

Use the JupyterHub server on the Google Cloud Platform,
provided by your designated instructor, for this assignment.
Complete the assignment by inserting your Python code wherever you see the string
"#INSERT YOUR ANSWER HERE." or "##CODE HERE##"

When you click the `File` button, from the top navigation bar, then select `Export Notebook As ...`,
a document (PDF or HTML format) will be generated that includes
 both the assignment content and the output of any embedded Python code chunks.

Using [these](https://www.ryerson.ca/courses/students/tutorials/assignments/) guidelines,
submit **both** the IPYNB and the exported file (PDF or HTML).
Failing to submit both files will be subject to mark deduction.

*****

### Question 1:

**a)** Write a code segment to create and print a two-dimensional 5x4 array (i.e. grid). The elements of the grid should be randomly selected from the inclusive interval \[-50, 50\].

In [6]:
!pip install numpy
import numpy as np
randArray = np.random.randint(-50, 50,(5, 4))
print(randArray)

[[  4  22  47  -7]
 [ -9 -14  36 -15]
 [ -9  16  13  29]
 [ -9 -33  30 -16]
 [-49  10  16  30]]


**b)** Write a code segment that searches the `Grid` object in `Q1a` for all the negative integers, and prints them.

In [22]:
randArrayNeg = randArray[randArray<0]
print(randArrayNeg)

[ -7  -9 -14 -15  -9  -9 -33 -16 -49]


**c)** Given that `iList = [1, -1, 2, -2]`, add each element of `iList` to its corresponding element of `Q1a` `Grid` row-wise.  

For example, if the Grid is equal to: $$\begin{pmatrix} 1 & 2 & 1 & 1 \\ 3 & 0 & 1 & 6 \\ 0 & 2 & 4 & 6 \\ 4 & 5 &0 & 2 \\ 3 & 6 & 4 & 3 \end{pmatrix}$$

Then the output should be:
$$\begin{pmatrix} 1+1 & 2-1 & 1+2 & 1-2 \\ 3+1 & 0-1 & 1+2 & 6-2 \\ 0+1 & 2-1 & 4+2 & 6-2 \\ 4+1 & 5-1 &0+2 & 2-2 \\ 3+1 & 6-1 & 4+2 & 3-2 \end{pmatrix}$$

In [15]:
iList = [1, -1, 2, -2]
sumArray = np.add(randArray,iList)
print(sumArray)

[[  5  21  49  -9]
 [ -8 -15  38 -17]
 [ -8  15  15  27]
 [ -8 -34  32 -18]
 [-48   9  18  28]]


**d)** Write a code segment that creates a ragged grid with three rows.  The first row contains 2 positions, the second row contains 4 positions, and the third row contains 6 positions. 

In [61]:
class iArray():
    def __init__(self, capacity, fillValue = 0):
        self._items = list()
        for count in range(int(capacity)):
            self._items.append(fillValue)

    def __getitem__(self, index):
        return self._items[index]

    def __setitem__(self, index, newItem):
        self._items[index] = newItem

    def getList(self):
        return self._items

    def __len__(self):
        return len(self._items)

    def __str__(self):
        return str(self._items)

    def __iter__(self):
        return iter(self._items)

class raggedGrid():
    def __init__(self, rows, columns, fillValue = 0):
        self._data = iArray(rows)
        for row in range(rows):
            self._data[row] = iArray(columns, fillValue)
        self.raggedList = []
        self.rGridList = []
        self._row = rows
        self._column = columns

    def setColumns(self):
        for row in range(self._row):
            rows = int(input('Number of columns for the row: ' ))
            columnLength =  iArray(rows)
            self.raggedList.append(columnLength)

    def getList(self):
        for item in self.raggedList:
           items = item.getList()
           self.rGridList.append(items)
        for array in self.rGridList:
            print(array)

    def getRows(self):
        return len(self._data)

    def getColumns(self):
        return len(self._data[0])

    def __getitem__(self, index):
        return self._data[index]

    def __str__(self):
        result = ""
        for row in range(self.getRows()):
            for col in range(self.getColumns()):
                result += str(self._data[row][col]) + ' '
            result += '\n'
        return result

theRaggedGrid = raggedGrid(3, 4) # Here we have the class produce a raggedGrid object of 3 rows and 4 columns
print(theRaggedGrid)
theRaggedGrid.setColumns() # Then we have the set columns method adjust the length of each respective column for each row, depending on the number of rows
rGridlist = theRaggedGrid.getList() #finally, we run the getList method that populates our list with what was present in the raggedList list, and iterates through them

0 0 0 0 
0 0 0 0 
0 0 0 0 



Number of columns for the row:  2
Number of columns for the row:  4
Number of columns for the row:  6


[0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]


*****



### Question 2:
A search algorithm `iSearch` and a variable `ilist` have been defined as follows:




In [46]:
def iSearch(target, lyst):
    left = 0
    right = len(lyst) - 1
    while left <= right:
        midpoint = (left + right) // 2
        if target == lyst[midpoint]:
            return midpoint
        elif target < lyst[midpoint]:
            right = midpoint - 1
        else:
            left = midpoint + 1
    return -1

iList = [11, 20, 29, 33, 41, 55, 56, 62, 66, 74, 88]

**a)**  If the target element is `11`, trace the values of the variables `left`, `right`, and `midpoint` after applying the `iSearch` algorithm to the `iList` structure. 



In [47]:
# First iteration:
# left: 0
# right: 10
# midpoint: 5
# Second iteration:
# left: 0
# right: 4
# midpoint: 2
# Third iteration:
# left: 0
# right: 1
# midpoint: 0

**b)**  Repeat the tracing process in `Q1a` for target element `55`.

In [48]:
# First iteration:
# left: 0
# right: 10
# midpoint: 5

# Since the target was found in the center of the list, 
# the function ceases and the index is returned.

**c)**  Why does the iSearch algorithm run faster in `Q1b` scenario than in `Q1a` scenario?

In [49]:
# This is because the target value we are searching for is 
# right at the centre of the list upon starting the first
# iteration. This is the best case scenario of a binary
# search algorithm with a time complexity of O(1).

**d)** Modify the `iSearch` algorithm, so it can run in `Q1a` scenario as fast as it does in `Q1b` scenario.

In [50]:
def iSearch(target, lyst):
    position = 0
    while position < len(iList):
        if target == iList[position]:
            return position
        else:
            position += 1
    return -1

iList = [11, 20, 29, 33, 41, 55, 56, 62, 66, 74, 88]

iSearch(11,iList)

# The iSearch algorithm has been modified to replicate the
# functionality of a linear search algorithm. This shall
# give us a time complexity identical to that of the 
# version of iSearch in Q1a; O(1).

0

**e)** For a problem of size $n$, if algorithm `X` performs $n^4$ instructions, and algorithm `Y` performs $2^n$ instructions.  At what point does one of the algorithms begin to be more efficient and perform better than the other? Justify your answer.

In [48]:
# The Algorithm Y denotes that the algorithm doubles with every new element introduced.

# The Algorithm X denotes that with every new element added, the algorithm rises astronomically 
# fast in the number of steps it would take to process every new element.

# Taking this information into account, the only point at which the Algorithm X is more efficient that Algorithm Y, is when the number of elements is 1. With
# every new element added to the respective algorithms, Algorithm Y will have a time complexity that is faster than that of Algorithm X.

# E.g. Algorithm X = (1)^4 gives us 1. When Algorithm X = (2)^4, we get 16.
# When Algorithm Y = 2^1, we get 2. When Algorithm Y = 2^2, we get 4.

*****

### Question 3:



Emulate the stack behaviour using the list data structure.

**a)** Complete the methods of the following `Stack` class according to their description

In [58]:
class Stack:
  def __init__(self):
    """ Initialize a new stack """
    self.elements = []
    self._top = -1
    self._size = 0

  def push(self, new_item):
    """ Append the new item to the stack """
    self.elements.append(new_item)
    self._top += 1
    self._size += 1
    self.elements[self._top] = new_item

  def pop(self):
    """ Remove and return the last item from the stack """
    oldItem = self.elements[self._top]
    self._top -= 1
    self._size -= 1
    return self.elements.pop()

  def size(self):
    """ Return the total number of elements in the stack """
    return len(self.elements)

  def is_empty(self):
    """ Return True if the stack is empty and False if it is not empty """
    if self.elements == 0:
        return True
    else:
        return False

  def peek(self):
    """ Return the element at the top of the stack or return None if the stack is empty """
    if self.elements != 0:
        return self.elements[self._top]
    else:
        return None

testStack = Stack()  # Testing stack object
testStack.push(2) # Testing operations
testStack.push(4)
testStack.push(6)
print(testStack.size())
print(testStack.pop()) # Testing operations
print(testStack.peek())
print(testStack.size())

3
6
4
2


**b)** Use the `Stack` class that you defined in `Q3a` to complete the code of the `is_valid()` function, which checks whether the order of the brackets of an arithmetic expression is correct. Some examples are given below:

In [18]:
exp1 = "(2+3)+(1-5)" # True
exp2 = "((3*2))*(7/3))" # False
exp3 = "(3*5))]" # False

In [56]:
def is_valid(exp):
    testStack2 = Stack()
    opening = ['(', '[', '{']
    closing = [')', ']', '}']

    for i in exp: # Iterate over every element in argument
        if i in opening:  # If element is in the opening list, add it to the stack.
            testStack2.push(i)  
        elif i in closing: # Should the element be in the closing bracket, and if the bracket at the index identified matches 
            # what is in the stack, remove it.
            j = closing.index(i)
            l = testStack2.size()
            if ((l > 0) and (opening[j] == testStack2.elements[l - 1])):
                testStack2.pop()  # Remove element from stack 
            else:
                return False
    l = testStack2.size()
    print(testStack2.size())
    if l == 0:
        return True
    else:
        return False

exp1 = "(2)+(-5)" # True
exp2 = "((2))*((3))" # True
exp3 = "(4))]" #False

print(is_valid(exp1))
print(is_valid(exp2))
print(is_valid(exp3))

0
True
0
True
False


**c)** Use the `Stack` class that you defined in `Q3a` to complete the code of the `count_pairs()` function, which returns the number of the valid bracket pairs of an arithmetic expression. Some examples are given below:

In [13]:
exp1 = "(2+3)+(1-5)" # 2 pairs
exp2 = "((([()])))" # 5 pairs
exp3 = "[([])" # 2 pairs

In [57]:
def count_pairs(exp):
    testStack3 = Stack()
    pairs = 0 # Decalre a variable to keep track of the pairs of brackets
    opening = ['(', '[', '{']
    closing = [')', ']', '}']
    

    for i in exp: # Iterate over every element in argument
        if i in opening: # If element is in the opening list, add it to the stack.
            testStack3.push(i)
        elif i in closing: # Upon reaching a closing bracket, take stock of the size of the stack.
            m = testStack3.size()
            if m == 0: # If the elements of the are 0, skip. If there is an element, remove it and have the pairs variable increment by 1.
                pass
            else:
                testStack3.pop()
                pairs += 1
    return pairs


exp1 = "(2+3)+(1-5)("  # 2 pairs
exp2 = "((([()])))"  # 5 pairs
exp3 = "[([])"  # 2 pairs

print(count_pairs(exp1))
print(count_pairs(exp2))
print(count_pairs(exp3))

2
5
2


### Question 4:
According to each method's documentation, complete the code of the `TextProcessor` class and its subclass `TextAnalyzer`.

In [54]:
class TextProcessor:
  def __init__(self, text):
    self.text = text
    self.stopWords = []
    
  def setStopWords(self, stopWords):
    ''' set stop words as recieved in the parameters '''
    self.stopWords = stopWords
    
  def getStopWords(self):
    ''' return stop words '''
    return self.stopWords
    
  def getUniqWords(self):
    return set(self.__text.split())

  def getFilteredText(self):
    ''' remove filter words from the text 
        return filtered text'''
    unfilteredText = self.text.split()
    i = 0
    
    while i < len(unfilteredText):
        if unfilteredText[i] in self.stopWords:
            unfilteredText.pop(i)
        else:
            i += 1
    filteredText = unfilteredText 
    return filteredText
    
class TextAnalyzer(TextProcessor):
  def __init__(self, text):
    ''' Construct the class '''
    TextProcessor.__init__(self, text)

  def getWordFrequency(self):
    ''' Call the getFilteredText() method
        Create a dictionary of words
        key = word and value= frequency
        return the dictionary'''
    filteredTxt = self.getFilteredText()
    wrdFrequency = {}
    for word in filteredTxt:
        if word in wrdFrequency:
            wrdFrequency[word] += 1
        else:
            wrdFrequency[word] = 1
    return wrdFrequency

ta = TextAnalyzer("a quick brown fox " + \
                  "a quick brown fox jumps " + \
                  "a quick brown fox jumps over " + \
                  "a quick brown fox jumps over the " + \
                  "a quick brown fox jumps over the lazy " + \
                  "a quick brown fox jumps over the lazy dog")
ta.setStopWords(['a', 'the'])
wrdFrequency = ta.getWordFrequency()
print(wrdFrequency)

{'quick': 6, 'brown': 6, 'fox': 6, 'jumps': 5, 'over': 4, 'lazy': 2, 'dog': 1}


Verify the correctness of your code using the following steps:

1. Instantiate the `TextAnalyzer` class by creating an object called `ta` as follows:

`ta = TextAnalyzer("a quick brown fox " + 
                  "a quick brown fox jumps " + 
                  "a quick brown fox jumps over " + 
                  "a quick brown fox jumps over the " + 
                  "a quick brown fox jumps over the lazy " + 
                  "a quick brown fox jumps over the lazy dog")`

2. Assign a list of stop words using the `setStopWords()` method:
`ta.setStopWords(['a', 'the'])`

3. Count the occurrences of each word using the `getWordFrequency()` method:
`ta.getWordFrequency()`

4. The output should be as follows
`{'quick': 6, 'brown': 6, 'fox': 6, 'jumps': 5, 'over': 4, 'lazy': 2, 'dog': 1}}`


#### This is the end of assignment 3